// Tokens para Dependency Injection
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_BALANCE_REPOSITORY = 'USER_BALANCE_REPOSITORY';
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';
export const POINTS_TRANSACTION_REPOSITORY = 'POINTS_TRANSACTION_REPOSITORY';
export const ORDER_STATUS_HISTORY_REPOSITORY = 'ORDER_STATUS_HISTORY_REPOSITORY';
export const WEBHOOK_LOG_REPOSITORY = 'WEBHOOK_LOG_REPOSITORY';
export const ALFRED_PAY_SERVICE = 'ALFRED_PAY_SERVICE';